services:
  independent:
    build: ./independent
    volumes:
      - ../tests:/tests
  mavennet:
    image: mavennet/mavennet-vc-cli:latest
    volumes:
      - ../tests:/tests
  tradeverifyd:
    image: ghcr.io/tradeverifyd/vc-jose-cose-test-suite:latest
    volumes:
      - ../tests:/tests

      
