services:
  decentralgabe:
    build: ./decentralgabe
    volumes:
      - ../tests:/tests
  Mavennet:
    image: mavennet/mavennet-vc-cli:latest
    volumes:
      - ../tests:/tests
  Tradeverifyd:
    image: ghcr.io/tradeverifyd/vc-jose-cose-test-suite:latest
    volumes:
      - ../tests:/tests

      
